name: Node CI/CD

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install, build
      run: |
        npm ci
        npm run build --if-present
      env:
        CI: true
    - name: npm test
      if: github.event_name == 'pull_request'
      run:
        npm test
      env:
        CI: true
    - name: npm gh-pages deploy
      if: github.event_name == 'push'
      run: |
        git config user.name $GITHUB_ACTOR
        git config user.email $GITHUB_ACTOR@pinkkis.com
        touch ./dist/.nojekyll
        npm run ghpublish -- --repo https://${{secrets.PERSONAL_TOKEN}}@github.com/$GITHUB_REPOSITORY.git -m "Automated Deploy started by $GITHUB_ACTOR"
