name: Node CI/CD

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install, build
      run: |
        npm ci
        npm run build --if-present
        touch ./dist/.nojekyll
      env:
        CI: true
    - name: npm test
      run:
        npm test
      if: github.event == 'pull_request'
      env:
        CI: true
    - name: Stash build artifact
      uses: actions/upload-artifact@v1
      if: github.event == 'pull_request'
      with:
        name: dist
        path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success() && github.event_name == 'push'
    steps:
      - name: Deploy to GH Pages
        uses: actions/download-artifact@v1
        with:
          name: dist
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist
